name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install ruff
      - name: Lint
        run: |
          ruff --version
          ruff check . || true
      - name: Syntax check
        run: |
          python -m py_compile $(git ls-files "**/*.py")


